# -*- coding: utf-8 -*-



import sys
import qdarkstyle
from PyQt5.QtGui import QIcon
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1085, 600)
        MainWindow.setMinimumSize(QtCore.QSize(1085, 600))
        MainWindow.setMaximumSize(QtCore.QSize(1085, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 70, 171, 51))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(540, 70, 231, 51))
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(250, 140, 821, 311))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.de_t_add = QtWidgets.QCommandLinkButton(self.widget)
        self.de_t_add.setObjectName("de_t_add")
        self.horizontalLayout.addWidget(self.de_t_add)
        self.sta_t_add = QtWidgets.QCommandLinkButton(self.widget)
        self.sta_t_add.setObjectName("sta_t_add")
        self.horizontalLayout.addWidget(self.sta_t_add)
        self.che_t_add = QtWidgets.QCommandLinkButton(self.widget)
        self.che_t_add.setObjectName("che_t_add")
        self.horizontalLayout.addWidget(self.che_t_add)
        self.mon_t_add = QtWidgets.QCommandLinkButton(self.widget)
        self.mon_t_add.setObjectName("mon_t_add")
        self.horizontalLayout.addWidget(self.mon_t_add)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.de_t_up = QtWidgets.QCommandLinkButton(self.widget)
        self.de_t_up.setObjectName("de_t_up")
        self.horizontalLayout_2.addWidget(self.de_t_up)
        self.sta_t_delete = QtWidgets.QCommandLinkButton(self.widget)
        self.sta_t_delete.setObjectName("sta_t_delete")
        self.horizontalLayout_2.addWidget(self.sta_t_delete)
        self.che_t_de = QtWidgets.QCommandLinkButton(self.widget)
        self.che_t_de.setObjectName("che_t_de")
        self.horizontalLayout_2.addWidget(self.che_t_de)
        self.mon_t_de = QtWidgets.QCommandLinkButton(self.widget)
        self.mon_t_de.setObjectName("mon_t_de")
        self.horizontalLayout_2.addWidget(self.mon_t_de)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.de_t_de = QtWidgets.QCommandLinkButton(self.widget)
        self.de_t_de.setObjectName("de_t_de")
        self.horizontalLayout_3.addWidget(self.de_t_de)
        self.sta_t_up = QtWidgets.QCommandLinkButton(self.widget)
        self.sta_t_up.setObjectName("sta_t_up")
        self.horizontalLayout_3.addWidget(self.sta_t_up)
        self.che_t_up = QtWidgets.QCommandLinkButton(self.widget)
        self.che_t_up.setObjectName("che_t_up")
        self.horizontalLayout_3.addWidget(self.che_t_up)
        self.mon_t_up = QtWidgets.QCommandLinkButton(self.widget)
        self.mon_t_up.setObjectName("mon_t_up")
        self.horizontalLayout_3.addWidget(self.mon_t_up)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.sa_t_up = QtWidgets.QCommandLinkButton(self.widget)
        self.sa_t_up.setObjectName("sa_t_up")
        self.horizontalLayout_4.addWidget(self.sa_t_up)
        self.sta_t_query = QtWidgets.QCommandLinkButton(self.widget)
        self.sta_t_query.setObjectName("sta_t_query")
        self.horizontalLayout_4.addWidget(self.sta_t_query)
        self.ac_t_add = QtWidgets.QCommandLinkButton(self.widget)
        self.ac_t_add.setObjectName("ac_t_add")
        self.horizontalLayout_4.addWidget(self.ac_t_add)
        self.ac_t_de = QtWidgets.QCommandLinkButton(self.widget)
        self.ac_t_de.setObjectName("ac_t_de")
        self.horizontalLayout_4.addWidget(self.ac_t_de)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(30, 140, 191, 309))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.de_t_query = QtWidgets.QCommandLinkButton(self.widget1)
        self.de_t_query.setObjectName("de_t_query")
        self.verticalLayout.addWidget(self.de_t_query)
        self.sa_t_auery = QtWidgets.QCommandLinkButton(self.widget1)
        self.sa_t_auery.setObjectName("sa_t_auery")
        self.verticalLayout.addWidget(self.sa_t_auery)
        self.check_t_query = QtWidgets.QCommandLinkButton(self.widget1)
        self.check_t_query.setObjectName("check_t_query")
        self.verticalLayout.addWidget(self.check_t_query)
        self.ac_t_query = QtWidgets.QCommandLinkButton(self.widget1)
        self.ac_t_query.setObjectName("ac_t_query")
        self.verticalLayout.addWidget(self.ac_t_query)
        self.mon_t_query = QtWidgets.QCommandLinkButton(self.widget1)
        self.mon_t_query.setObjectName("mon_t_query")
        self.verticalLayout.addWidget(self.mon_t_query)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1085, 30))
        self.menubar.setObjectName("menubar")
        self.sys1 = QtWidgets.QMenu(self.menubar)
        self.sys1.setObjectName("sys1")
        self.dep1 = QtWidgets.QMenu(self.menubar)
        self.dep1.setObjectName("dep1")
        self.staff1 = QtWidgets.QMenu(self.menubar)
        self.staff1.setObjectName("staff1")
        self.salary1 = QtWidgets.QMenu(self.menubar)
        self.salary1.setObjectName("salary1")
        self.checking1 = QtWidgets.QMenu(self.menubar)
        self.checking1.setObjectName("checking1")
        self.month1 = QtWidgets.QMenu(self.menubar)
        self.month1.setObjectName("month1")
        self.activity1 = QtWidgets.QMenu(self.menubar)
        self.activity1.setObjectName("activity1")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.sys = QtWidgets.QAction(MainWindow)
        self.sys.setObjectName("sys")
        self.sta_secret = QtWidgets.QAction(MainWindow)
        self.sta_secret.setObjectName("sta_secret")
        self.de_query = QtWidgets.QAction(MainWindow)
        self.de_query.setObjectName("de_query")
        self.de_add = QtWidgets.QAction(MainWindow)
        self.de_add.setObjectName("de_add")
        self.de_up = QtWidgets.QAction(MainWindow)
        self.de_up.setObjectName("de_up")
        self.de_de = QtWidgets.QAction(MainWindow)
        self.de_de.setObjectName("de_de")
        self.staff_add = QtWidgets.QAction(MainWindow)
        self.staff_add.setObjectName("staff_add")
        self.sta_de = QtWidgets.QAction(MainWindow)
        self.sta_de.setObjectName("sta_de")
        self.sta_query = QtWidgets.QAction(MainWindow)
        self.sta_query.setObjectName("sta_query")

        self.sta_up = QtWidgets.QAction(MainWindow)
        self.sta_up.setObjectName("sta_up")
       
        self.sta_good = QtWidgets.QAction(MainWindow)
        self.sta_good.setObjectName("sta_good")

        self.sta_bad = QtWidgets.QAction(MainWindow)
        self.sta_bad.setObjectName("sta_bad")

        self.sa_query = QtWidgets.QAction(MainWindow)
        self.sa_query.setObjectName("sa_query")
        self.sa_up = QtWidgets.QAction(MainWindow)
        self.sa_up.setObjectName("sa_up")
        self.che_query = QtWidgets.QAction(MainWindow)
        self.che_query.setObjectName("che_query")
        self.che_add = QtWidgets.QAction(MainWindow)
        self.che_add.setObjectName("che_add")
        self.che_up = QtWidgets.QAction(MainWindow)
        self.che_up.setObjectName("che_up")
        self.che_de = QtWidgets.QAction(MainWindow)
        self.che_de.setObjectName("che_de")
        self.mon_query = QtWidgets.QAction(MainWindow)
        self.mon_query.setObjectName("mon_query")
        self.mon_add = QtWidgets.QAction(MainWindow)
        self.mon_add.setObjectName("mon_add")
        self.mon_up = QtWidgets.QAction(MainWindow)
        self.mon_up.setObjectName("mon_up")
        self.mon_de = QtWidgets.QAction(MainWindow)
        self.mon_de.setObjectName("mon_de")
        self.ac_query = QtWidgets.QAction(MainWindow)
        self.ac_query.setObjectName("ac_query")
        self.ac_de = QtWidgets.QAction(MainWindow)
        self.ac_de.setObjectName("ac_de")
        self.ac_add = QtWidgets.QAction(MainWindow)
        self.ac_add.setObjectName("ac_add")
        self.ac_up = QtWidgets.QAction(MainWindow)
        self.ac_up.setObjectName("ac_up")
        self.sys1.addAction(self.sys)
        self.sys1.addAction(self.sta_secret)
        self.dep1.addAction(self.de_query)
        self.dep1.addAction(self.de_add)
        self.dep1.addAction(self.de_up)
        self.dep1.addAction(self.de_de)
        self.staff1.addAction(self.staff_add)
        self.staff1.addAction(self.sta_de)
        self.staff1.addAction(self.sta_query)
        self.staff1.addAction(self.sta_up)
        self.staff1.addAction(self.sta_good)
        self.staff1.addAction(self.sta_bad)

        self.salary1.addAction(self.sa_query)
        self.salary1.addAction(self.sa_up)

        self.checking1.addAction(self.che_query)
        self.checking1.addAction(self.che_add)
        self.checking1.addAction(self.che_up)
        self.checking1.addAction(self.che_de)
        self.month1.addAction(self.mon_query)
        self.month1.addAction(self.mon_add)
        self.month1.addAction(self.mon_up)
        self.month1.addAction(self.mon_de)
        self.activity1.addAction(self.ac_query)
        self.activity1.addAction(self.ac_de)
        self.activity1.addAction(self.ac_add)
        self.activity1.addAction(self.ac_up)
        self.menubar.addAction(self.sys1.menuAction())
        self.menubar.addAction(self.dep1.menuAction())
        self.menubar.addAction(self.staff1.menuAction())
        self.menubar.addAction(self.salary1.menuAction())
        self.menubar.addAction(self.checking1.menuAction())
        self.menubar.addAction(self.month1.menuAction())
        self.menubar.addAction(self.activity1.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "人事管理系统"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">员工快捷功能区</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">管理员快捷功能区</span></p></body></html>"))
        self.de_t_add.setText(_translate("MainWindow", "部门添加"))
        self.sta_t_add.setText(_translate("MainWindow", "员工添加"))
        self.che_t_add.setText(_translate("MainWindow", "缺勤添加"))
        self.mon_t_add.setText(_translate("MainWindow", "月度成就添加"))
        self.de_t_up.setText(_translate("MainWindow", "部门修改"))
        self.sta_t_delete.setText(_translate("MainWindow", "员工删除"))
        self.che_t_de.setText(_translate("MainWindow", "缺勤删除"))
        self.mon_t_de.setText(_translate("MainWindow", "月度成就删除"))
        self.de_t_de.setText(_translate("MainWindow", "部门删除"))
        self.sta_t_up.setText(_translate("MainWindow", "员工修改"))
        self.che_t_up.setText(_translate("MainWindow", "缺勤修改"))
        self.mon_t_up.setText(_translate("MainWindow", "月度成就修改"))
        self.sa_t_up.setText(_translate("MainWindow", "工资修改"))
        self.sta_t_query.setText(_translate("MainWindow", "员工查看"))

        self.ac_t_add.setText(_translate("MainWindow", "活动添加"))
        self.ac_t_de.setText(_translate("MainWindow", "活动删除"))
        self.de_t_query.setText(_translate("MainWindow", "查看部门"))
        self.sa_t_auery.setText(_translate("MainWindow", "查看工资"))
        self.check_t_query.setText(_translate("MainWindow", "查看缺勤"))
        self.ac_t_query.setText(_translate("MainWindow", "查看活动"))
        self.mon_t_query.setText(_translate("MainWindow", "查看月度成就"))
        self.sys1.setTitle(_translate("MainWindow", "系统管理"))
        self.dep1.setTitle(_translate("MainWindow", "部门管理"))
        self.staff1.setTitle(_translate("MainWindow", "员工管理"))
        self.salary1.setTitle(_translate("MainWindow", "工资管理"))
        self.checking1.setTitle(_translate("MainWindow", "考勤管理"))
        self.month1.setTitle(_translate("MainWindow", "月度成就记录"))
        self.activity1.setTitle(_translate("MainWindow", "活动管理"))
        self.sys.setText(_translate("MainWindow", "管理员管理"))
        self.sta_secret.setText(_translate("MainWindow", "员工密码修改"))
        self.de_query.setText(_translate("MainWindow", "查看部门"))
        self.de_add.setText(_translate("MainWindow", "添加部门"))
        self.de_up.setText(_translate("MainWindow", "修改部门信息"))
        self.de_de.setText(_translate("MainWindow", "删除部门信息"))
        self.staff_add.setText(_translate("MainWindow", "添加员工"))
        self.sta_de.setText(_translate("MainWindow", "删除员工"))
        self.sta_query.setText(_translate("MainWindow", "查看员工信息"))
        self.sta_up.setText(_translate("MainWindow", "修改员工信息"))
        self.sta_good.setText(_translate("MainWindow", "查看月度优秀员工"))
        self.sta_bad.setText(_translate("MainWindow", "查看月度不佳员工"))

        self.sa_query.setText(_translate("MainWindow", "查看工资"))
        self.sa_up.setText(_translate("MainWindow", "修改工资信息"))
        self.che_query.setText(_translate("MainWindow", "查看缺勤记录"))
        self.che_add.setText(_translate("MainWindow", "添加缺勤记录"))
        self.che_up.setText(_translate("MainWindow", "修改缺勤记录"))
        self.che_de.setText(_translate("MainWindow", "删除缺勤记录"))
        self.mon_query.setText(_translate("MainWindow", "查看月度成就记录"))
        self.mon_add.setText(_translate("MainWindow", "添加月度成就记录"))
        self.mon_up.setText(_translate("MainWindow", "修改月度成就记录"))
        self.mon_de.setText(_translate("MainWindow", "删除月度成就记录"))
        self.ac_query.setText(_translate("MainWindow", "查看活动"))
        self.ac_de.setText(_translate("MainWindow", "删除活动"))
        self.ac_add.setText(_translate("MainWindow", "添加活动信息"))
        self.ac_up.setText(_translate("MainWindow", "修改活动信息"))



if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    app.setWindowIcon(QIcon("./source/staff.png"))
    app.setStyleSheet(qdarkstyle.load_stylesheet_pyqt5())
    ui = Ui_MainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())